# Introdução

Na literatura sobre economia regional, há poucos trabalhos analisando a moeda e o seu papel para o desenvolvimento regional. Modelos como o neoclássico, o de causação cumulativa e o de insumo-produto, não consideram o impacto da moeda e de variáveis financeiras. Segundo Crocco *et al*., [-@crocco2006], essas variáveis são tratadas em modelos econométricos como exógenas, de forma que afetam a determinação regional de renda em razão das características específicas de cada região. Logo, a moeda e os fluxos monetários têm sido explicados como o resultado da diferença entre as regiões e não como os causadores dessa diferença. Amado [-@amado2006] também destaca que variáveis monetárias e financeiras são recorrentemente negligenciadas em estudos sobre a questão regional.

Além disso, há uma lacuna na literatura quanto ao papel da moeda no desenvolvimento urbano, sobretudo quanto aos fatores distributivos e qualitativos na oferta de crédito dentro das cidades. Trabalhos como o de Hashimoto, Pažitka e Wójcik [-@hashimoto2022], Hashimoto e Wójcik [-@hashimoto2021], Tupy [-@tupy2016], Crocco [-@crocco2012] e Parr e Budd [-@parr] focaram na questão locacional e hierárquica dos serviços financeiros, utilizando-se de dados de emprego no setor financeiro e número de agências para determinar coeficientes de localização e centralidade dessas atividades. Outros trabalhos, como os de Memarian *et al*., [-@memarian2023] e Chauvet e Jacolin [-@chauvet2017] exploraram o impacto da concentração bancária no acesso ao crédito por parte das firmas, ao utilizarem dados do endividamento das firmas e obstáculos geográficos até a agência bancária. Todas essas contribuições tangenciam de alguma forma o papel da moeda no desenvolvimento urbano, mas não discutem concentração de crédito e desigualdade financeira dentro das cidades.

Por conta disso, faz-se necessário um trabalho que dê palco central para a distribuição do crédito no espaço urbano, revisite as contribuições passadas sobre a questão regional do crédito e do setor bancário e utilize do grande volume de dados disponíveis nos dias atuais para testar hipóteses, realizar análises espaciais e dar condições para formulação de políticas públicas de acesso à crédito no âmbito urbano.

Nesse sentido, ainda há muitas questões a se explorar e responder sobre o tema da moeda no espaço: As concentrações bancárias já identificadas por Selmier [-@selmier2016], Tupy [-@igor], Dow [-@dow2012], Amado [-@amado2006] e outros autores se repetem no meio urbano? Há diferenças quantitativas e qualitativas na oferta de crédito entre distritos de um mesmo município? Há discriminação na oferta de serviços financeiros entre regiões periféricas e centrais de uma metrópole? Volume e qualidade do crédito impactam na renda per capita dos bairros/distritos da cidade?

Diante dos questionamentos e da lacuna literária, o presente trabalho pretende aprofundar as discussões sobre centralidade financeira no espaço urbano, por meio de uma análise espacial empírica e exploratória do setor bancário do município de São Paulo, em 2010. Essa análise é importante para compreender como a oferta de crédito está dispersa no espaço e como ela influencia o desenvolvimento econômico e social das cidades, servindo de base para formulação de políticas de desenvolvimento regional no combate às desigualdades regionais.

Para atingir esses objetivos será necessário construir uma base de dados com os arquivos disponibilizados mensalmente pelo BACEN da estatística bancária de cada agência (ESTBAN) e georreferenciar esses dados. Com isso, será possível agrupar os dados por setor censitário da malha territorial de São Paulo (IBGE) e cruzar com os dados de renda e domicílio do CENSO 2010. Depois, calcularemos alguns índices de localização, distribuição, qualidade e diversidade do crédito, que serão apresentados na seção de metodologia. Em seguida, realizaremos uma análise exploratória desses dados, por meio de técnicas de clusters e análise de componentes principais. Além disso, estimaremos um modelo econométrico espacial (SLX) com os índices criados para mensurar o impacto da oferta de crédito local e dos vizinhos mais próximos na renda per capita das regiões. Por fim, avaliaremos e discutiremos os resultados encontrados, sob o referencial pós-keynesiano.

Esse trabalho divide-se em 5 capítulos, incluindo essa introdução. No próximo, são tratados os aspectos teóricos importantes para a análise exploratória e empírica que será realizada neste trabalho, abordando os fundamentos de Economia Monetária
de Produção, da caracterização de Centro e Periferia e das principais questões existentes sobre os Serviços financeiros no meio urbano. A metodologia é apresentada no terceiro capítulo, subdividida em seções para tratar separadamente a fonte dos dados e cada um dos métodos utilizados. No capítulo 4 são apresentados os resultados, discutindo-os. Por fim, são apresentadas as considerações finais do trabalho.

# ASPECTOS TEÓRICOS

## *Economia Monetária de Produção*

Segundo Keynes [-@keynes73b], vivemos em uma economia monetária de produção, em que a moeda exerce papel fundamental nas decisões econômicas dos agentes, pois empresários decidem produzir e contratar fatores de produção com expectativa de ganhar dinheiro com sua produção. Como não há nenhum mecanismo que garanta que a contratação de fatores será totalmente compensada pela venda do produto gerado e, considerando um contexto de incerteza sobre o futuro, os agentes podem optar por não gastar esse ativo, mantendo-o na sua forma líquida.

Dessa forma, em uma economia monetária, o empresário possui interesse no dinheiro que será gerado a partir de suas atividades produtivas. Seu objetivo principal é aumentar sua riqueza de forma geral, ou seja, em sua forma monetária. Ele tomará a decisão de expandir sua produção se acreditar que isso resultará em um aumento de sua renda. A escolha entre oferecer ou não trabalho é, na verdade, uma decisão sobre como utilizar sua riqueza, seja investindo-a na produção ou mantendo-a na forma mais líquida (mantendo em dinheiro). Nesse tipo de economia, o produtor não é guiado pelo volume de produto que espera obter, mas sim pelas oportunidades alternativas de aumentar ou preservar sua riqueza [@keynes73a].

Carvalho [-@carvalho92] apresentou uma síntese das características de uma economia monetária de produção, elencando seis princípios fundamentais de sua operação que garantem à moeda as funções de reserva de valor e de liquidez:

- (i) Princípio da produção: o objetivo das firmas é gerar lucro monetário, o interesse não está na quantidade de produto produzida, mas no montante de dinheiro gerado.

- (ii) Princípio da dominância estratégica: dada a escassez do capital em relação ao trabalho, trabalhadores e empresas encontram-se em condições desiguais no mercado, o que também é válido para o mercado de crédito, pois o poupador não consegue induzir o empresário a se endividar. Porém, no que diz respeito à obtenção de crédito, as empresas têm mais sucesso, mesmo que precisem oferecer taxas de juros mais altas aos potenciais credores. Isso demonstra claramente a predominância das empresas nos mercados.

- (iii) Príncipio da temporalidade: O princípio da temporalidade na atividade econômica estabelece uma ordem sequencial no processo produtivo: a decisão de produzir ocorre antes da produção em si, que por sua vez precede a venda. Esse princípio é fundamentado na ideia de tempo histórico, irreversível, adotado pelos teóricos pós-keynesianos. Essa concepção reconhece o tempo como uma entidade contínua, sempre avançando do passado em direção ao futuro. Em outras palavras, as decisões tomadas em um determinado momento do tempo não podem ser desfeitas e têm implicações para o futuro.

- (iv) Princípio da não-ergodicidade (da incerteza): o sistema econômico caminha, ao longo do tempo, de um passado irrevogável para um futuro incerto, estatisticamente imprevisível.

- (v) Princípio da não pré-conciliação dos planos: não existe um plano perfeito que possa coordenar todos os mercados e determinar exatamente a quantidade a ser produzida com base na demanda futura. Os agentes econômicos podem tentar reduzir a incerteza recorrendo a contratos futuros denominados em moeda. Esses contratos permitem que os agentes fixem acordos antecipados para a compra ou venda de determinados bens ou serviços, proporcionando algum grau de segurança em relação às transações futuras.

- (vi) Princípio das propriedades da moeda: Para que seja possível a realização de contratos futuros denominados em moeda, a moeda deve possuir duas propriedades fundamentais: elasticidade de produção e substituição próximas de zero. Essas características garantem à moeda sua função como reserva de valor e liquidez. Ao afirmar que a elasticidade de produção e substituição da moeda é próxima de zero, significa que um aumento na demanda por moeda não resulta em um aumento em sua disponibilidade e que nenhuma outra forma de ativo pode desempenhar suas funções. Dessa forma, a moeda adquire um caráter único e essencial na economia capitalista.

## *Centro e periferia*

Após uma análise dos elementos fundamentais das economias monetárias de produção, é possível realizar uma caracterização geral entre economias centrais e periféricas. Ao comparar essas economias, pode-se observar que as economias centrais tendem a ter trajetórias de crescimento mais estáveis, com a variável dinâmica sendo endógena. Além disso, apresentam uma menor propensão a importar, instituições mais desenvolvidas, mercados com maior liquidez de ativos e bases sólidas para a disseminação de informações. Isso resulta em um menor nível de incerteza. Em termos de estrutura produtiva, nas economias centrais a produção está concentrada principalmente nos setores secundário e terciário. Já nas economias periféricas, a produção se concentra nos setores primário e terciário [@dow82].

Ao analisar a caracterização geral das economias centrais e periféricas, fica evidente uma tendência de maior preferência pela liquidez nas economias periféricas em comparação com as centrais. Isso ocorre devido à maior incerteza e à menor desenvoltura dos arranjos institucionais nas periferias. Consequentemente, a criação de meios de pagamento nessas economias pode enfrentar desafios, uma vez que os multiplicadores são menores devido à preferência pela liquidez mais pronunciada por parte dos agentes na periferia. É importante ressaltar que, ao contrário dos multiplicadores nacionais, os multiplicadores regionais são fortemente influenciados pelos vazamentos no fluxo financeiro entre diferentes regiões. Esses vazamentos podem ser de natureza real, como o saldo comercial, ou de natureza financeira, como as transações na conta de capitais. De todo modo, ambos tendem a drenar liquidez das economias periféricas em direção às economias centrais [@chick88].

Para Amado [-@amado2006], os bancos são fundamentais nesse contexto, pois são os principais criadores de liquidez. Sendo assim, a autora defende que uma análise que procure observar o comportamento dos agentes em relação à moeda e aos limites que a liquidez pode gerar ao processo de crescimento de determinada economia deve ter por base a análise do comportamento dos bancos como criadores de liquidez.

Sobre a tendência ao dreno de liquidez das regiões periféricas para as centrais, Dow [-@dow82] pontua dois problemas vividos pelos bancos na periferia: (i) perdem reservas continuamente para o centro e (ii) perdem mais reservas que os bancos do centro para o público em geral, já que este tem maior demanda por liquidez. Desse modo, tanto há problemas com o multiplicador bancário quanto com o multiplicando, e ambos tendem a limitar a criação de liquidez.

Pensando que a liquidez é o primeiro limite à decisão de investir, o processo de crescimento da periferia será impedido por um limite de liquidez e o crescimento do centro é facilitado pelo mesmo motivo.

Amado [-@amado2006] verificou um processo de concentração bancária e financeira (fusões bancárias) nos anos 1990, que prejudicou diretamente as economias periféricas, ao reforçar as restrições de liquidez que essas economias enfrentam. De acordo com a autora, as economias periféricas sofrem constantes vazamentos em seus fluxos financeiros. Esses vazamentos são drenados para as regiões centrais, que passam a apresentar vantagens comparativas em relação à periferia, por terem acesso a um volume maior de liquidez. Dessa forma, os bancos centrais ficam mais receosos em estender crédito à periferia, por terem expectativas menos sólidas em relação a essas regiões. Além disso, os bancos da periferia tendem a estender crédito a atividades que sejam mais fortemente relacionadas com a própria região, com intuito de evitar perda de reservas. Para Amado [-@amado2006], esse processo de concentração levará os bancos que assumem os bancos regionais a redirecionar suas atividades para as regiões em que possuem vantagens comparativas, como aconteceu com três bancos de caráter regional que foram absorvidos por bancos das regiões centrais: Econômico pelo Excel, Banorte pelo Bandeirantes e Bamerindus pelo HSBC.

Martin e Sunley [-@martin2015] destacam que o acesso das empresas a empréstimos financeiros varia de acordo com a localidade, principalmente devido às práticas discriminatórias das instituições bancárias em relação ao financiamento. Dessa forma, empresas localizadas em regiões economicamente deprimidas podem ser consideradas de alto risco pelas instituições financeiras, resultando na recusa de crédito. O que reforça a importância dos bancos de caráter regional.

De acordo com Selmier [-@selmier2016], essa característica é crucial para entender a capacidade do sistema bancário brasileiro de manter altas taxas de lucro. O autor destaca que ao longo do tempo, o sistema bancário do Brasil tem sido dominado por quatro grandes bancos. Essa estrutura de mercado oligopolizada proporciona estabilidade, uma vez que os lucros dos grandes bancos são sustentados, permitindo que eles se concentrem em seus mercados domésticos. Selmier [-@selmier2016] afirma que os "Big Four" do Brasil apresentam margens de lucro e de juros líquidos igualmente elevadas.

## *O papel da centralidade no meio urbano*

Além da diferenciação entre centro e periferia, é importante compreender a dinâmica espacial dos serviços financeiros. Parr e Budd [-@parr] se baseiam na Teoria do Lugar Central, desenvolvida por Christaller [-@christaller], para explicar a localização dos serviços financeiros.

A Teoria do Lugar Central foi originalmente desenvolvida para explicar a localização de atividades de varejo e não de serviços financeiros. No entanto, a Teoria do Lugar Central pode ser útil para entender a organização espacial de serviços financeiros, especialmente em relação à hierarquia urbana e à distribuição de centros financeiros em diferentes níveis de centros urbanos. Segundo Crocco [-@crocco2010], a centralidade de uma região, que depende de fatores como tamanho da população, renda e diversidade industrial, pode influenciar a atividade bancária na região.

Parr e Budd [-@parr] argumentam que as economias de escala e escopo desempenham um papel significativo na decisão de onde uma atividade no setor financeiro deve ser localizada. Isso tem um impacto crucial nos mercados financeiros, instituições intermediárias e produtos financeiros, resultando em efeitos notáveis na eficácia estratégica e comparativa das atividades financeiras. Além disso, esses fatores também restringem o número de locais disponíveis para a prestação de determinados serviços financeiros.

Memarian *et al*. [-@memarian2023] mostram que a informação, crucial para a tomada de decisões nos mercados financeiros, não é facilmente transferível pelo espaço, e os centros urbanos se beneficiam das economias de aglomeração e do fluxo de informações facilitado, o que reduz os custos de globais de transação, a assimetria de informações e os riscos de risco moral. O que corrobora com a tese de que há formação de centros financeiros nos centros urbanos.

Embora o acesso ao crédito para as empresas seja facilitado pela formação das centralidades no centro urbano [@memarian2023; @lee2018; @wood2005], a grande concentração financeira pode desfavorecer o público periférico, que enfrentará maiores problemas de acesso, devido aos maiores custos de transação e transporte, já que muitos dos serviços financeiros só podem ser contratados de forma presencial, exigindo um contato face-a-face.

Mesmo em grandes centros urbanos, com alta densidade populacional, há heterogeneidade espacial, como demonstrado por Memarian *et al.* [-@memarian2023], que utilizaram imagens de satélites para identificar obstáculos de transporte e de crescimento da malha urbana. Outros estudos, como os de Pereira *et al.*[-@pereira2019desigualdades] e Pereira [-@pereira_distributive_2018] mostram como o acesso a oportunidades urbanas é desigual e como há diferentes custos de transportes envolvidos para atingir as oportunidades (dentre elas, as financeiras), que estão concentradas no centro.